### ISSUE TITLE
Set multiple values at once...

### ISSUE THREAD

**Issue by VoltVisionFrenchy** [atlewee/node-red-contrib-sacn#2]
Hello!
I am trying your sACN library with Node-Red and I have it working by doing the "set single value", but I was wondering what is the most graceful way to use an array to update all 512 values of a universe at the same time?  Would it be possible to load in a JSON array representing the entire universe or some other method?  Thanks! -VoltVisionFrenchy

**Comment by atlewee** [comment]
I did a quick implementation of array support in v0.0.6
It just overrides the whole universe with supplied json array of values directly.
Set universe on config node, and just pass it an array in the payload. e.g: [ 128, 0, 128 ] writes the first 3 values of that universe.  You can add up to 512 values to the array.
