### ISSUE TITLE
Add Multicast Support?

### ISSUE THREAD

**Issue by VoltVisionFrenchy** [atlewee/node-red-contrib-sacn#3]
Hello it took me a while to figure out that you have this library setup to use only unicast.  In other words you need to know and set the unique IPaddress of the destination "host" in order for it to work.  I was hoping this library would support Multicast, which is more similar to the Pub/Sub model.  Then it is possible to have many different receiving nodes that can come and go without needing to know (or care about) their IPaddresses.  Is Multicast support on the roadmap?  Thanks! -VoltVisionFrenchy

**Comment by atlewee** [comment]
I do not have access to equipment for testing just now, but I can maybe do it in a couple of weeks.
It seems straight forward to get multicast going as well.. 
I don't use it myself, thats why its not implemented yet :)

**Comment by atlewee** [comment]
I found out it was even easier than first look. Multicast is now supported in v0.0.7 :)
You simply enter a universe insted of the host/IP address.  (Integer value between 1-63999)
