### ISSUE TITLE
Error re: port, no matter what value I use

### ISSUE THREAD

**Issue by terryhonn** [atlewee/node-red-contrib-sacn#6]
Hello, excited to use this node to send data to E131 Christmas light controllers from Home Assistant via Node-Red, however I get the following error regardless of port value (integers, strings, etc):

1/29/2020, 1:30:19 PMnode: 21011854.abd208
msg : error
"RangeError: Port should be >= 0 and < 65536. Received [ '5568' ]."

Something in my configuration, or a problem introduced with updates to the Node-Red addon in Home Assistant, or something else?

Thanks in advance!

**Comment by atlewee** [comment]
Thanks for the input! Sorry late reply. It is fixed in 0.0.8
