### ISSUE TITLE
Sacn flow doesnt work anymore after update node-red

### ISSUE THREAD

**Issue by MikeJollie21** [atlewee/node-red-contrib-sacn#7]
I was forced to reinstall node red , now i am on the latest version, but the Scan flow gives the following error, i filed in the right ip and port:

"RangeError: Port should be >= 0 and < 65536. Received [ '5568' ]."

Node-RED version: v1.0.6
Node.js  version: v12.16.3
![Knipsel](https://user-images.githubusercontent.com/48416973/82840285-4075bc80-9ed2-11ea-982f-641d05d4c375.PNG)

**Comment by mylesie** [comment]
I just came across this same issue tonight.  Has there been any work around or fix found?  I would love to implement this into my flow for sensors into a LX console SACN in view.

**Comment by aroslanov** [comment]
Just got the same error after moving to another server. Does anyone have any workarounds for this problem?

**Comment by aroslanov** [comment]
Got working solution from the Reddit user i8beef:

Just a guess, but he's turning the port into an array before sending it into the underlying client connection here, which looks like incorrect usage: [https://github.com/atlewee/node-red-contrib-sacn/blob/master/sacn-config.js#L14](https://github.com/atlewee/node-red-contrib-sacn/blob/master/sacn-config.js#L14)
If you edit the node_modules/node-red-contrib-sacn/sacn-config.js and removed those brackets, restarted node-red, and then went and edited / resaved the server config, that might get you working, but that is just a temporary hack that'll be undone as soon as the node_modules is rebuilt, etc.

**Comment by MikeJollie21** [comment]
@aroslanov  Sorry for the late reply, 
You are right , i removed those brackets and it worked thank you very much, unless it's a temporary fix it will help me out,
up to @atlewee to update this in his code.

**Comment by atlewee** [comment]
Thank you for creating the issue.. Fixed in v0.0.8 :)
